#!/bin/sh
set -e

if [ "$1" = "remove" ] && command -v systemctl >/dev/null; then
  systemctl stop saugra.service >/dev/null 2>&1 || true
  systemctl disable saugra.service >/dev/null 2>&1 || true
fi

exit 0
